//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.454
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericAdapter
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int btnSave = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int idView = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int imageItem = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int listMotorCycle = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int nameView = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int txtInput = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int txtItem = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int txtView1 = 2131034114;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int IdAndNameListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SimpleListItem = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int Add_a_motorcycle_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Id = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Name = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int Save = 2130968577;
			
			private String()
			{
			}
		}
	}
}
